version: '3'

services:
  app:
    build: .
    container_name: wialon_login_bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./screenshots:/app/screenshots
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - POSTGRES_DB=wialon_db
      - POSTGRES_USER=wialon
      - POSTGRES_PASSWORD=wialonpass
    networks:
      - wialon_network
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "tor & sleep 5 && python run_bot.py"

  db:
    image: postgres:15-alpine
    container_name: wialon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wialon
      POSTGRES_PASSWORD: wialonpass
      POSTGRES_DB: wialon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wialon_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wialon -d wialon_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  wialon_network:
    driver: bridge
