"""Add SavedCredentials and update TokenHistory

Revision ID: 1d8ec27adcbb
Revises: bd8e276c04ee
Create Date: 2025-04-25 09:30:32.315965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8ec27adcbb'
down_revision: Union[str, None] = 'bd8e276c04ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.add_column('token_history', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('token_history', sa.Column('type', sa.String(), nullable=False))
    op.add_column('token_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('token_history', sa.Column('extra_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('token_history', 'extra_data')
    op.drop_column('token_history', 'created_at')
    op.drop_column('token_history', 'type')
    op.drop_column('token_history', 'user_name')
    op.drop_table('saved_credentials')
    # ### end Alembic commands ###
