"""add created_at to master_tokens

Revision ID: ed077937a534
Revises: 9e2a0746012c
Create Date: 2025-04-18 08:39:47.866521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed077937a534'
down_revision: Union[str, None] = '9e2a0746012c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('child_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('child_tokens', sa.Column('creation_method', sa.String(), nullable=True))
    op.add_column('child_tokens', sa.Column('access_rights', sa.String(), nullable=True))
    op.add_column('child_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('child_tokens', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('master_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('master_tokens', sa.Column('creation_method', sa.String(), nullable=True))
    op.add_column('master_tokens', sa.Column('access_rights', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('master_tokens', 'access_rights')
    op.drop_column('master_tokens', 'creation_method')
    op.drop_column('master_tokens', 'created_at')
    op.drop_column('child_tokens', 'duration')
    op.drop_column('child_tokens', 'expires_at')
    op.drop_column('child_tokens', 'access_rights')
    op.drop_column('child_tokens', 'creation_method')
    op.drop_column('child_tokens', 'created_at')
    op.drop_table('token_history')
    # ### end Alembic commands ###
